# Generated by Django 4.0.1 on 2022-01-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_info', models.CharField(max_length=1000)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('edit_at', models.DateField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms6.flagmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=100)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms6.newsmodel')),
            ],
        ),
    ]
