# Generated by Django 4.0.1 on 2022-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms6', '0003_alter_commentmodel_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='edit_at',
            field=models.DateField(auto_now=True),
        ),
    ]
