# Generated by Django 4.0.1 on 2022-01-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms6', '0004_alter_newsmodel_edit_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='edit_at',
            field=models.DateField(default=None),
        ),
    ]
