# Generated by Django 4.0.1 on 2022-01-21 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='description',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adv',
            name='expire_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adv',
            name='views',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterModelTable(
            name='advstatus',
            table='advstatus',
        ),
    ]
