# Generated by Django 4.0.1 on 2022-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_adv_description_adv_expire_at_alter_adv_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='expire_at',
            field=models.TimeField(),
        ),
    ]
