# Generated by Django 4.0.1 on 2022-01-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_adv_expire_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterModelTable(
            name='adv',
            table='adv',
        ),
        migrations.AddField(
            model_name='adv',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.user'),
        ),
    ]
