# Generated by Django 4.0.1 on 2022-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_user_alter_adv_table_adv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adv',
            name='expire_at',
            field=models.DateField(),
        ),
    ]
