# Generated by Django 4.0.1 on 2022-01-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_adv_create_at_alter_adv_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv',
            name='create_at',
            field=models.DateField(),
        ),
    ]
